on: 
  workflow_dispatch:
    pull_request:
        branches:
          - master
        paths:
          - .github/workflows/manual-trigger.yml
          - src/job.yml

name: Manually trigger an Azure Machine Learning job

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
      - name: Trigger Azure Machine Learning job
        run: az ml job create --file job.yml --web --resource-group ${{secrets.AZURE_RESOURCE_GROUP}} --workspace-name ${{secrets.AZURE_WORKSPACE_NAME}}
        working-directory: src