name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    schedule:
      - cron: "0 0/24 * * *"
    pull_request:
      branches:
        - master
      paths:
        - .github/workflows/manual-trigger.yml
        - cli/setup.sh
      
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

